### ISSUE TITLE
Compilation issues with vtk 8.2.0 under Ubuntu 16.04

### ISSUE THREAD

**Issue by kenavolic** [pdhahn/vtkFLTK-V8.x-F1.4#1]
Hi,

I fixed a compilation issue under my configuration.

# Env

- os: ubuntu: 16.04
- vtk version: 8.2.0
- g++ version: 7.4.0

# Location

> src/vtkFLTKOpenGLRenderWindow.cxx:120:1: note: in expansion of macro ‘vtkStandardNewMacro’

# Issue

Pure virtual methods in parent class (SetWindowInfo, SetParentInfo, SetNextWindowInfo) are not implemented. This is due to the fact that the signature in vtkWindow takes a const char* and the override only a char*

# Fix

First, you can mark these 3 methods with the override key work in vtkFLTKOpenGLRenderWindow to get an early more explicit message. Then, just change the signature!

Hope this help! Thanks for your work!

**Comment by pdhahn** [comment]
OK thank you for this. I think the signature for these methods must have changed in VTK between 8.1 and 8.2. I will implement your suggested fix (based on test with constant VTK_MINOR_VERSION) and test under both versions, then check it in.
